from .llm_interface import chatgpt_interface

def ai_advice(preferences, best_match):
    system_role = """
    You are a Financial Advisor. The user will have a set of attributes generated by a survey and a system 
    will provide investment vehicles based on the user profile. 
    You will receive the user attributes and the results. Your job is to give two to three sentences of very simple explanations of why you 
    would recommend that investment vehicle, and then give a few very specific options on what to invest in. Answer all in Japanese.
    """

    user_attributes = "\n".join([f"{key}: {value:.2f}%" for key, value in preferences.items()])
    investment_strategy = f"Recommended vehicle: {best_match}"

    user_text = f"-- User attributes --\n{user_attributes}\n-- Investment strategy --\n{investment_strategy}\n"
    user_text += "Why is this investment good for me? Include an explanation for all the investment recommendations."

    # Call AI model
    response = chatgpt_interface(system_role=system_role, user=user_text)
    return response
